---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: fred-cilium-gw
  namespace: fred
spec:
  gatewayClassName: cilium
  listeners:
  - protocol: HTTP
    port: 80
    name: fred
    allowedRoutes:
      namespaces:
        from: Same
