apiVersion: v1
kind: Service
metadata:
  name: fredv3
  labels:
    app.kubernetes.io/name: fredv3
  annotations:
     service.cilium.io/global: "true"
     service.cilium.io/affinity: "remote"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: fredv3
